[package]
edition.workspace      = true
name                   = "demo"
publish                = false
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow.workspace             = true
butler.workspace             = true
tokio                        = { features = ["macros", "rt-multi-thread", "signal", "time"], workspace = true }
tracing-subscriber.workspace = true
